export const districts = [
  { value: "01", district: "Balod" },
  { value: "02", district: "Baloda Bazar" },
  { value: "03", district: "Balrampur" },
  { value: "04", district: "Bastar" },
  { value: "05", district: "Bemetara" },
  { value: "06", district: "Bijapur" },
  { value: "07", district: "Bilaspur" },
  { value: "08", district: "Dantewada" },
  { value: "09", district: "Dhamtari" },
  { value: "10", district: "Durg" },
  { value: "11", district: "Gariaband" },
  { value: "12", district: "Gaurela-Pendra-Marwahi" },
  { value: "13", district: "Janjgir-Champa" },
  { value: "14", district: "Jashpur" },
  { value: "15", district: "Kabirdham" },
  { value: "16", district: "Khairagarh-Chhuikhadan-Gandai" },
  { value: "17", district: "Kondagaon" },
  { value: "18", district: "Korba" },
  { value: "19", district: "Koriya" },
  { value: "20", district: "Mahasamund" },
  { value: "21", district: "Manendragarh-Chirimiri-Bharatpur" },
  { value: "22", district: "Mohla-Manpur-Ambagarh Chowki" },
  { value: "23", district: "Mungeli" },
  { value: "24", district: "Narayanpur" },
  { value: "25", district: "Raigarh" },
  { value: "26", district: "Raipur" },
  { value: "27", district: "Rajnandgaon" },
  { value: "28", district: "Sakti" },
  { value: "29", district: "Sarangarh-Bilaigarh" },
  { value: "30", district: "Sukma" },
  { value: "31", district: "Surajpur" },
  { value: "32", district: "Surguja" },
  { value: "33", district: "Uttar Bastar Kanker" }
];
