export const assembly = [
  { value: "01", Assembly_name: "Bharatpur - Sonhat (ST)", random_value: 67 },
  { value: "02", Assembly_name: "Manendragarh", random_value: 41 },
  { value: "03", Assembly_name: "Baikunthpur", random_value: 88 },
  { value: "04", Assembly_name: "Premnagar", random_value: 24 },
  { value: "05", Assembly_name: "Bhatgaon", random_value: 93 },
  { value: "06", Assembly_name: "Pratappur (ST)", random_value: 15 },
  { value: "07", Assembly_name: "Ramanujganj (ST)", random_value: 59 },
  { value: "08", Assembly_name: "Samri (ST)", random_value: 36 },
  { value: "09", Assembly_name: "Lundra (ST)", random_value: 78 },
  { value: "10", Assembly_name: "Ambikapur", random_value: 52 },
  { value: "11", Assembly_name: "Sitapur (ST)", random_value: 19 },
  { value: "12", Assembly_name: "Jashpur (ST)", random_value: 65 },
  { value: "13", Assembly_name: "Kunkuri (ST)", random_value: 83 },
  { value: "14", Assembly_name: "Pathalgaon (ST)", random_value: 44 },
  { value: "15", Assembly_name: "Lailunga (ST)", random_value: 97 },
  { value: "16", Assembly_name: "Raigarh", random_value: 31 },
  { value: "17", Assembly_name: "Sarangarh (SC)", random_value: 14 },
  { value: "18", Assembly_name: "Kharsia", random_value: 73 },
  { value: "19", Assembly_name: "Dharamjaigarh (ST)", random_value: 55 },
  { value: "20", Assembly_name: "Rampur (ST)", random_value: 99 },
  { value: "21", Assembly_name: "Korba", random_value: 27 },
  { value: "22", Assembly_name: "Katghora", random_value: 68 },
  { value: "23", Assembly_name: "Pali - Tanakhar (ST)", random_value: 43 },
  { value: "24", Assembly_name: "Marwahi (ST)", random_value: 71 },
  { value: "25", Assembly_name: "Kota", random_value: 17 },
  { value: "26", Assembly_name: "Lormi", random_value: 95 },
  { value: "27", Assembly_name: "Mungeli (SC)", random_value: 30 },
  { value: "28", Assembly_name: "Takhatpur", random_value: 84 },
  { value: "29", Assembly_name: "Bilha", random_value: 47 },
  { value: "30", Assembly_name: "Bilaspur", random_value: 96 },
  { value: "31", Assembly_name: "Beltara", random_value: 28 },
  { value: "32", Assembly_name: "Masturi (SC)", random_value: 61 },
  { value: "33", Assembly_name: "Akaltara", random_value: 13 },
  { value: "34", Assembly_name: "Janjgir - Champa", random_value: 79 },
  { value: "35", Assembly_name: "Sakti", random_value: 50 },
  { value: "36", Assembly_name: "Chandrapur", random_value: 35 },
  { value: "37", Assembly_name: "Jaijaipur", random_value: 80 },
  { value: "38", Assembly_name: "Pamgarh (SC)", random_value: 54 },
  { value: "39", Assembly_name: "Saraipali (SC)", random_value: 25 },
  { value: "40", Assembly_name: "Basna", random_value: 98 },
  { value: "41", Assembly_name: "Khallari", random_value: 18 },
  { value: "42", Assembly_name: "Mahasamund", random_value: 82 },
  { value: "43", Assembly_name: "Bilaigarh (SC)", random_value: 42 },
  { value: "44", Assembly_name: "Kasdol", random_value: 62 },
  { value: "45", Assembly_name: "Baloda Bazar", random_value: 70 },
  { value: "46", Assembly_name: "Bhatapara", random_value: 72 },
  { value: "47", Assembly_name: "Dharsiwa", random_value: 29 },
  { value: "48", Assembly_name: "Raipur Rural", random_value: 56 },
  { value: "49", Assembly_name: "Raipur City West", random_value: 33 },
  { value: "50", Assembly_name: "Raipur City North", random_value: 81 },
  { value: "51", Assembly_name: "Raipur City South", random_value: 12 },
  { value: "52", Assembly_name: "Arang (SC)", random_value: 48 },
  { value: "53", Assembly_name: "Abhanpur", random_value: 90 },
  { value: "54", Assembly_name: "Rajim", random_value: 21 },
  { value: "55", Assembly_name: "Bindranawagarh (ST)", random_value: 63 },
  { value: "56", Assembly_name: "Sihawa (ST)", random_value: 39 },
  { value: "57", Assembly_name: "Kurud", random_value: 85 },
  { value: "58", Assembly_name: "Dhamtari", random_value: 46 },
  { value: "59", Assembly_name: "Sanjari Balod", random_value: 70 },
  { value: "60", Assembly_name: "Dondi Lohara (ST)", random_value: 26 },
  { value: "61", Assembly_name: "Gunderdehi", random_value: 53 },
  { value: "62", Assembly_name: "Patan", random_value: 92 },
  { value: "63", Assembly_name: "Durg - Rural", random_value: 11 },
  { value: "64", Assembly_name: "Durg City", random_value: 76 },
  { value: "65", Assembly_name: "Bhilai Nagar", random_value: 38 },
  { value: "66", Assembly_name: "Vaishali Nagar", random_value: 60 },
  { value: "67", Assembly_name: "Ahiwara (SC)", random_value: 86 },
  { value: "68", Assembly_name: "Saja", random_value: 23 },
  { value: "69", Assembly_name: "Bemetara", random_value: 58 },
  { value: "70", Assembly_name: "Nawagarh (SC)", random_value: 75 },
  { value: "71", Assembly_name: "Pandariya", random_value: 34 },
  { value: "72", Assembly_name: "Kawardha", random_value: 89 },
  { value: "73", Assembly_name: "Khairagarh", random_value: 40 },
  { value: "74", Assembly_name: "Dongargarh (SC)", random_value: 66 },
  { value: "75", Assembly_name: "Rajnandgaon", random_value: 16 },
  { value: "76", Assembly_name: "Dongargaon", random_value: 94 },
  { value: "77", Assembly_name: "Khujji", random_value: 77 },
  { value: "78", Assembly_name: "Mohla - Manpur (ST)", random_value: 32 },
  { value: "79", Assembly_name: "Antagarh (ST)", random_value: 87 },
  { value: "80", Assembly_name: "Bhanupratappur (ST)", random_value: 45 },
  { value: "81", Assembly_name: "Kanker (ST)", random_value: 64 },
  { value: "82", Assembly_name: "Keshkal (ST)", random_value: 22 },
  { value: "83", Assembly_name: "Kondagaon (ST)", random_value: 57 },
  { value: "84", Assembly_name: "Narayanpur (ST)", random_value: 74 },
  { value: "85", Assembly_name: "Bastar (ST)", random_value: 37 },
  { value: "86", Assembly_name: "Jagdalpur", random_value: 69 },
  { value: "87", Assembly_name: "Chitrakot (ST)", random_value: 49 },
  { value: "88", Assembly_name: "Dantewada (ST)", random_value: 91 },
  { value: "89", Assembly_name: "Bijapur (ST)", random_value: 20 },
  { value: "90", Assembly_name: "Konta (ST)", random_value: 51 }
];
 